import type { ServiceRequest, State } from './domain';
const base = {
  technician: null,
  visit: null,
  linkedTo: null,
  candidate: null,
  clarification: '',
  events: [],
};
const rows: ServiceRequest[] = [
  {
    ...base,
    id: 'R101',
    received: '2026-09-30T16:10',
    channel: 'Email',
    customer: 'C01',
    message: 'Cold-room unit keeps stopping. Stored goods could be affected.',
    original: 'Unassigned',
    title: 'Cold-room keeps stopping',
    equipment: 'Cold-room unit (identifier unconfirmed)',
    priority: 'urgent',
    status: 'open',
  },
  {
    ...base,
    id: 'R102',
    received: '2026-10-01T08:20',
    channel: 'WhatsApp',
    customer: 'C02',
    message: 'Can you confirm when someone is coming for yesterday’s pump request?',
    original: 'Assigned T1; no visit time recorded',
    title: 'Pump visit needs a time',
    equipment: 'Pump (identifier unconfirmed)',
    priority: 'normal',
    status: 'assigned',
    technician: 'T1',
  },
  {
    ...base,
    id: 'R103',
    received: '2026-09-30T11:00',
    channel: 'Phone',
    customer: 'C03',
    message: 'Routine inspection request for next week.',
    original: 'Open',
    title: 'Routine inspection next week',
    equipment: 'Inspection scope to agree',
    priority: 'planned',
    status: 'open',
  },
  {
    ...base,
    id: 'R104',
    received: '2026-10-01T08:25',
    channel: 'Email',
    customer: 'C01',
    message: 'Following up on the cold-room fault reported yesterday.',
    original: 'New row; may duplicate R101',
    title: 'Cold-room follow-up',
    equipment: 'Cold-room unit (identifier unconfirmed)',
    priority: 'unknown',
    status: 'open',
    candidate: 'R101',
  },
  {
    ...base,
    id: 'R105',
    received: '2026-10-01T08:30',
    channel: 'Phone',
    customer: 'C04',
    message: 'Machine not working. Please call us.',
    original: 'No equipment identifier or urgency recorded',
    title: 'Machine down; details missing',
    equipment: '',
    priority: 'unknown',
    status: 'open',
    clarification: 'Call C04: which machine, is it safe, and what operation is affected?',
  },
  {
    ...base,
    id: 'R106',
    received: '2026-09-29T14:00',
    channel: 'Email',
    customer: 'C05',
    message: 'We are waiting for the replacement part and an update.',
    original: 'Assigned T2; waiting for part',
    title: 'Replacement part; update needed',
    equipment: 'Equipment awaiting part (identifier unconfirmed)',
    priority: 'normal',
    status: 'waiting',
    technician: 'T2',
  },
  {
    ...base,
    id: 'R107',
    received: '2026-09-30T15:00',
    channel: 'WhatsApp',
    customer: 'C06',
    message: 'Thanks, the unit is running again.',
    original: 'Still marked in progress under T3',
    title: 'Unit running; confirm completion',
    equipment: 'Repaired unit (identifier unconfirmed)',
    priority: 'normal',
    status: 'in-progress',
    technician: 'T3',
  },
  {
    ...base,
    id: 'R108',
    received: '2026-10-01T08:40',
    channel: 'Email',
    customer: 'C07',
    message: 'Please send someone today for a pressure warning.',
    original: 'Unassigned; details need clarification',
    title: 'Pressure warning; clarify risk',
    equipment: '',
    priority: 'unknown',
    status: 'open',
    clarification:
      'Call C07: identify the equipment, warning reading, and safety impact. Do not assume it is safe to run.',
  },
];
export const createSeed = (): State => ({
  version: 1,
  requests: rows.map((row) => ({ ...structuredClone(row), events: [] })),
});
